### ISSUE TITLE
rephrasing in /get-started under PlatformIO IDE tab

### ISSUE THREAD

**Issue by aksell** [platformio/platformio-web#11]
> You no need to install PIO Core separately,

could maybe be replaced with

>You don’t need to install PIO Core separately,

![peek 2018-02-18 09-33](https://user-images.githubusercontent.com/22766894/36349950-f97805ec-148e-11e8-9c6a-e7366d45946f.gif)

**Comment by ivankravets** [comment]
Thanks! Fixed!
