### ISSUE TITLE
ST Nucleo L053R8 is not 48 MHz

### ISSUE THREAD

**Issue by jcw** [platformio/platformio-web#12]
(this is probably the wrong repository, but I don't know which one it should go to)

On the [Embedded boards](https://platformio.org/boards) page, "ST Nucleo L053R8" is listed as 48 MHz. This should be 32 MHz.

**Comment by ivankravets** [comment]
Thanks! Fixed in https://github.com/platformio/platform-ststm32/commit/3f5de06b1037c706bccdeb06fa41bc76bbb22db5

Will be updated on the site very soon.

**Comment by jcw** [comment]
Everyone else would have rejected this issue and told me to go re-submit in the proper repository.
Hats off to you, Ivan, for just fixing this little detail and moving on :)

**Comment by ivankravets** [comment]
@jcw We are with Community, you help us make PIO better and better 😊
