### ISSUE TITLE
Allow search by library ID.

### ISSUE THREAD

**Issue by skorokithakis** [platformio/platformio-web#9]
I've been trying to get to the documentation of a library from a library ID (because I found the library from `platformio lib search <term>`, and it turned out to be quite hard. I would propose one or all of the following:

* Add links to the documentation (or platformio.org page) in `platformio lib show`.
* Allow lookups by `id:101` on the platformio.org search page.
* Allow the URLs on platformio.org to redirect to the lib page even with just the ID (so http://platformio.org/lib/show/107/ would redirect to http://platformio.org/lib/show/107/I2Cdevlib-MPU6050/ rather than return a 404).

Thanks!

**Comment by ivankravets** [comment]
You can use temporary http://platformio.org/lib/show/101/any-text-here

**Comment by simonegiacomelli** [comment]
I had the same problem too.

I found a workaround. Just use google with this kind of search

site:platformio.org/lib/show/457

457 was the library I was looking for

**Comment by ivankravets** [comment]
Done!

https://platformio.org/lib/search?query=id:13
